version: '3'

services:
  frontend:
    image: bohdancho/imaginaer-frontend
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - backend
    networks: 
      - app

  backend:
    image: bohdancho/imaginaer-backend
    build: ./backend
    networks:
      - app

networks:
  app:
