CREATE TABLE IF NOT EXISTS user (
  id INTEGER PRIMARY KEY,
  username STRING NOT NULL UNIQUE,
  password STRING NOT NULL
);

CREATE TABLE IF NOT EXISTS session (
  id INTEGER PRIMARY KEY,
  expires DATETIME NOT NULL,
  user_id INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id)
);
