CREATE TABLE user (
  id INTEGER PRIMARY KEY,
  username STRING NOT NULL UNIQUE,
  password STRING NOT NULL
);

CREATE TABLE session (
  token STRING PRIMARY KEY,
  expires DATETIME NOT NULL,
  user_id INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id)
);
